### ISSUE TITLE
fix caption indici

### ISSUE THREAD

**Issue by CorradoLanera** [UBESP-DCTV/covid19ita#10]
negli indici terapia intensiva per tamponi, l'etichetta della legenda è  rimasta codificata

**Comment by CorradoLanera** [comment]
@ilariaprosepe, nella sezione indici (c'è un unico modulo per tutti, al momento) i titoletti sono rimasti in italiano, sono quelli dentro le funzioni `h2()` in `eng-mod_ind_ita.R`

**Comment by ilariaprosepe** [comment]
> @ilariaprosepe, nella sezione indici (c'è un unico modulo per tutti, al momento) i titoletti sono rimasti in italiano, sono quelli dentro le funzioni h2() in eng-mod_ind_ita.R

@CorradoLanera ho sistemato gia' ieri sera! Chiudo questo issue?
