### ISSUE TITLE
Feature request: more mathematical models?

### ISSUE THREAD

**Issue by vguard** [UBESP-DCTV/covid19ita#26]
Mi chiedo se si può aggiungere qualche modello e qualche stima di parametri: k, t di raddoppio, R0...
Fit di esponenziali? O di distribuzioni normale/Weibull? Oltre alla scala logaritmica già richiesta. Apprezzo molto la Loess!
Buon lavoro
Vincenzo

**Comment by vguard** [comment]
Ah, li ho trovati, ma solo dopo avere partecipato al Webinar AIE e avere sentito Danila Azzolina. Ben nascosti...
Bel lavoro, grazie

**Comment by CorradoLanera** [comment]
ottimo grazie, segnalo l'opzione di dare più diffusione a tali contenuti e cercare di rendere più evidenti tali sezioni. Grazie per il feedback

**Comment by spanun** [comment]
@vguard  mi puoi dire dove sono?

**Comment by CorradoLanera** [comment]
> @vguard mi puoi dire dove sono?

Nella sezione **Indici principali** sono riportati alcuni indici, nella sezione **In evidenza** alcuni studi tematici (spesso per singole regioni) che sono stati effettuati.
