### ISSUE TITLE
Color consistency

### ISSUE THREAD

**Issue by lucavd** [UBESP-DCTV/covid19ita#33]
Colors and legends' organization is not consistent between National and Regional graphs

**NATIONAL**
![image](https://user-images.githubusercontent.com/7904152/77988509-d51dcd00-731c-11ea-84ea-371819efa6eb.png)

**REGIONAL**
![image](https://user-images.githubusercontent.com/7904152/77988574-fda5c700-731c-11ea-97d1-f7d46b31bade.png)

**Comment by lucavd** [comment]
Also, the legend title is not consistent having "Misura" and "Misurazione" titles

**Comment by CorradoLanera** [comment]
Both issues fixed. Update online from this evening.
