### ISSUE TITLE
covid19.icuve?

### ISSUE THREAD

**Issue by eborgnine** [UBESP-DCTV/covid19ita#89]
```
ERROR: dependency ‘covid19.icuve’ is not available for package ‘covid19ita’
```

what's covid19.icuve?  Google doesn't know what it is, so unless google is wrong it doesn't exist!

**Comment by CorradoLanera** [comment]
It is a private package to fetching reserved data. I have listed it wrongly as dependency. This evening I will move it under `Enhance`, so it cannot be required in the standard installation process nor when using `dependency = TRUE`.

Sorry for the inconvenient, and thank you for let me know it.

**Comment by CorradoLanera** [comment]
@eborgnine can you confirm the issue is solved?

**Comment by eborgnine** [comment]
yes, it's working now



Patrick Brown
Centre for Global Health Research, St Michael's Hospital
Department of Statistical Sciences, University of Toronto
pbrown.ca
