### ISSUE TITLE
Couldn't normalize path in `addResourcePath`

### ISSUE THREAD

**Issue by CorradoLanera** [UBESP-DCTV/covid19ita#93]
@fpirotti, the app stopped work remotely (but it works fine locally).

The error is:

```
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'font-awesome-5.3.1'; `directoryPath` = ''
```
I have attached the log here.
[covid19ita-shiny-20210923-151736-42823.log](https://github.com/UBESP-DCTV/covid19ita/files/7217936/covid19ita-shiny-20210923-151736-42823.log)

Searching from "font-awesome" across the whole source code, it finds [these two](https://github.com/UBESP-DCTV/covid19ita/search?q=font-awesome) results only, both inside the map module (they are two only because one is in Italian and the other in English).

The issue seams related to rstudio/shiny/issues/2407, and ramnathv/htmlwidgets/issues/320.

Can you help to find a solution?

**Comment by fpirotti** [comment]
Hi @CorradoLanera 
 We can safely remove/comment out the following:
eng-mod_maps.R - line 94-98
mod_maps.R - line 108-115
Worse case scenario the icon in the play/pause will not be visible, but we can fix that later, the important part is that the app loads correctly.
F

**Comment by fpirotti** [comment]
Thanx Corrado, I think it is ok to comment only the lines mentioned - not necessary to comment other parts... the htmldependency simply adds CSS references to the HTML, font-awesome icons... if these dependencies are not present, it will fall back to simple icons or a square, so it should be ok to leave the rest un commented.

**Comment by CorradoLanera** [comment]
Grazie @fpirotti , a posto. Per il momento allora chiudo questo issue, in caso se poi vuoi fare delle modifiche al modulo aprine tu un'altro.
